local NS = _G.AzerothWaypointNS

NS.CHANGELOG_DATA = {
    {
        version = "4.0.0",
        sections = {
            { title = "AzerothWaypoint rename and v4 reset", entries = {
                { text = "AzerothWaypoint replaces ZygorWaypoint across the addon TOC, namespace, media paths, help text, settings text, chat output, and `/awp` command surface.", level = 1 },
                { text = "Legacy v1/v2/v3 SavedVariables migration/repair paths were removed. `ApplyDBDefaults` now fills and normalizes the new database shape instead of carrying old upgrade logic.", level = 1 },
                { text = "Startup detects an old `ZygorWaypoint` addon still loaded/installed and warns about the conflict. `StartZygorWaypointConflictReminders` repeats a reminder until the old addon is disabled/removed.", level = 1 },
                { text = "TomTom is the only required dependency. Zygor Guides Viewer, APR, WoWPro, Mapzeroth, FarstriderLib, FarstriderLibData, and WorldQuestTab are optional integrations.", level = 1 },
            }},
            { title = "Startup prompts and first-run guidance", entries = {
                { text = "Added a Zygor arrow conflict prompt: when Zygor's own Waypoint Arrow is enabled, AWP offers a one-click \"Turn Off Zygor Arrow\" action or a decline option.", level = 1 },
                { text = "The Zygor arrow prompt is delayed at startup so it does not collide with other startup popups.", level = 1 },
            }},
            { title = "Guide provider system", entries = {
                { text = "Replaced the old Zygor-only guide path with a guide provider dispatcher.", level = 1 },
                { text = "Added built-in providers for:", level = 1 },
                { text = "Zygor Guides Viewer.", level = 2 },
                { text = "Azeroth Pilot Reloaded.", level = 2 },
                { text = "WoWPro.", level = 2 },
                { text = "Providers register label, icon, tint, size, visibility, extraction, activation token, hooks, and debug behavior through the provider API.", level = 1 },
                { text = "Guide provider state is tracked separately per provider, with active-provider persistence and passive guide queue projection.", level = 1 },
                { text = "Explicit guide activation can switch the active guide provider while manual/transient route authority remains higher priority.", level = 1 },
                { text = "Guide queues can exist for providers that are visible but not currently controlling the active route.", level = 1 },
                { text = "Provider and presentation files are loaded from the TOC, but provider-specific code exits early when the source addon is not loaded/enabled.", level = 1 },
            }},
            { title = "Zygor integration", entries = {
                { text = "Preserved Zygor parity including:", level = 1 },
                { text = "Zygor guide resolver.", level = 2 },
                { text = "Canonical target extraction.", level = 2 },
                { text = "LibRover-backed routing backend.", level = 2 },
                { text = "Zygor POI takeover.", level = 2 },
                { text = "Compact viewer chrome.", level = 2 },
                { text = "Starlight and Stealth arrow themes.", level = 2 },
                { text = "Moved Zygor POI support out of `bridge/takeovers/tomtom_bridge_zygor_poi_takeover.lua` into `integrations/guides/zygor/zygor_poi.lua`.", level = 1 },
                { text = "Zygor provider code now participates in the same provider arbitration system as APR and WoWPro.", level = 1 },
                { text = "Zygor guide presentation continues to use the existing resolver, facts, live context, presentation context, snapshots, cases, scans, and resolution modules.", level = 1 },
            }},
            { title = "APR integration", entries = {
                { text = "Added APR provider support under `integrations/guides/apr/`.", level = 1 },
                { text = "Extracts active step, route coordinates, title, visibility, activation token, and guide queue projection.", level = 1 },
                { text = "APR coordinates are treated as APR world-space coordinates, not 0-100 map percentages.", level = 1 },
                { text = "Added `apr_presentation.lua` for actionable APR overlay titles:", level = 1 },
                { text = "`Accept 'Quest Name'`", level = 2 },
                { text = "`Turn in 'Quest Name'`", level = 2 },
                { text = "exact objective text for progress steps when available.", level = 2 },
                { text = "Multi-quest pickup/turn-in steps select one actionable quest title at a time instead of cramming multiple quest names into one title.", level = 1 },
                { text = "APR helper text uses `ExtraLineText`, `ExtraLineText2`, and APR text/locale resolution helpers.", level = 1 },
                { text = "Quest-backed APR steps set quest semantics and quest icon hints only when a real quest ID is found.", level = 1 },
                { text = "Added APR debug output for action key, quest IDs, primary quest ID, title source, subtext source, final title, final subtext, and coordinates.", level = 1 },
                { text = "Added `integrations/guides/apr/APR-Route-Syntax.md` as local implementation reference material.", level = 1 },
            }},
            { title = "WoWPro integration", entries = {
                { text = "Added WoWPro provider support under `integrations/guides/wowpro/`.", level = 1 },
                { text = "Extracts active step index, guide ID, map ID, coordinate strings, visibility, and queue projection.", level = 1 },
                { text = "WoWPro coordinates are parsed as 0-100 percentages and converted to AWP's 0-1 coordinate format.", level = 1 },
                { text = "Multi-coordinate WoWPro steps choose the final destination target used by WoWPro's own routing logic.", level = 1 },
                { text = "Added `wowpro_presentation.lua` for actionable WoWPro overlay titles:", level = 1 },
                { text = "accept steps.", level = 2 },
                { text = "turn-in steps.", level = 2 },
                { text = "completion/progress steps.", level = 2 },
                { text = "note/instruction steps.", level = 2 },
                { text = "travel, use, and loot actions.", level = 2 },
                { text = "Completion steps can use the WoWPro note as title while objective progress becomes subtext, such as `1/6 Blackrock Worg slain`.", level = 1 },
                { text = "Quest progress subtext prefers WoWPro objective data and falls back to shared Blizzard quest helpers.", level = 1 },
                { text = "WoWPro TomTom and `C_Map.SetUserWaypoint` signals are handled as guide provider input, not generic manual queue adoption.", level = 1 },
                { text = "Added WoWPro debug output for action, raw step, note, QO data, quest IDs, primary quest ID, title/subtext sources, final title, and final subtext.", level = 1 },
                { text = "Added `integrations/guides/wowpro/WoWPro-Syntax.md` as local implementation reference material.", level = 1 },
            }},
            { title = "Routing backends", entries = {
                { text = "Routing is now planned by selectable backends instead of being tied directly to one guide addon.", level = 1 },
                { text = "Added four routing backends:", level = 1 },
                { text = "TomTom Direct: always-available single-leg fallback.", level = 2 },
                { text = "Farstrider: FarstriderLib/FarstriderLibData routing with portals, boats, zeppelins, items, spells, and availability invalidation.", level = 2 },
                { text = "Mapzeroth: Mapzeroth graph routing with travel nodes and instance entrance support.", level = 2 },
                { text = "Zygor: LibRover-backed routing for Zygor users.", level = 2 },
                { text = "TomTom Direct: always-available single-leg fallback. PURE TomTom, no pathfinding.", level = 2 },
                { text = "First-run backend priority is Zygor > Farstrider > Mapzeroth > TomTom Direct.", level = 1 },
                { text = "Invalid or unavailable backend selections fall back to Direct.", level = 1 },
                { text = "The backend dropdown exposes backend availability and disabled/missing states.", level = 1 },
                { text = "Route signatures include guide provider/source details so identical coordinates from different providers do not merge into the wrong authority state.", level = 1 },
                { text = "Added backend-specific fallback handling for missing planners, no-path results, empty plans, timeout fallbacks, and direct fallback legs.", level = 1 },
            }},
            { title = "Routing engine rewrite", entries = {
                { text = "Replaced the old monolithic bridge sync model with modular `bridge/routing/` files.", level = 1 },
                { text = "Added explicit routing layers:", level = 1 },
                { text = "Authority: current manual/guide ownership and persisted manual route state.", level = 2 },
                { text = "Identity: normalized metadata for manual routes, map pins, quests, area POIs, vignettes, taxis, dig sites, housing plots, Zygor POIs, and external callers.", level = 2 },
                { text = "Backend: pluggable route planning.", level = 2 },
                { text = "Carrier: TomTom Arrow synchronization.", level = 2 },
                { text = "Presentation: shared title, subtext, icon hint, semantic kind, and route leg display data.", level = 2 },
                { text = "Persistent active-route source now survives reload/login when possible.", level = 1 },
                { text = "Route environment tracking captures zone, real zone, subzone, minimap zone, indoor state, and route gate matching.", level = 1 },
                { text = "The v3 TickUpdate heartbeat is no longer the primary route driver; v4 routing reacts through explicit evaluator and invalidation paths. Cleaner and more efficient.", level = 1 },
                { text = "Improved TomTom carrier synchronization, external clear detection, route invalidation, and guide visibility hooks.", level = 1 },
            }},
            { title = "Special travel actions", entries = {
                { text = "Added route legs for items, spells, toys, hearthstones, and similar travel actions.", level = 1 },
                { text = "Added a secure special travel button that replaces the arrow when the current route leg requires a clickable action.", level = 1 },
                { text = "Added combat-safe secure attribute handling.", level = 1 },
                { text = "Added route replan suppression while a special action is being prepared or clicked.", level = 1 },
                { text = "Added Special Travel Button Scale in the TomTom Arrow options section.", level = 1 },
                { text = "Added special travel button preview metadata and help media.", level = 1 },
            }},
            { title = "Manual queues", entries = {
                { text = "Added queue modules under `bridge/routing/queues/` for state, items, routing, policy, projection, and snapshots.", level = 1 },
                { text = "Added persistent manual queues with stable queue IDs, labels, active item index, item metadata, and route restoration.", level = 1 },
                { text = "Added destination queues for multi-destination manual-click flows.", level = 1 },
                { text = "Added route queues for single route-like entries.", level = 1 },
                { text = "Added transient queues for short-lived external sources such as SilverDragon, RareScanner, and gossip-style (such as guard directions) transient destinations.", level = 1 },
                { text = "Added guide-projected queues so active guide destinations appear in the queue panel even when another source controls the route.", level = 1 },
                { text = "Manual queues stay listed when guide routing is active.", level = 1 },
                { text = "Guide queues stay listed when a manual queue is active.", level = 1 },
                { text = "`StopUsingManualQueue` lets a queue stop controlling the active route without deleting that queue.", level = 1 },
                { text = "Queue follow-up advances to the next queued destination after clear/arrival.", level = 1 },
                { text = "Imported `/ttpaste` and similar multi-waypoint batches are always stored and routed as ordered AWP queues.", level = 1 },
            }},
            { title = "Queue UI", entries = {
                { text = "Added a waypoint queue side tab on the world map.", level = 1 },
                { text = "Added queue list view, detail view, summary panel, scrollable rows, and queue sections.", level = 1 },
                { text = "Queue sections include transient queues, manual queues, and user guide queues.", level = 1 },
                { text = "Added queue activation, queue deactivation, queue clearing, destination activation, destination removal, final-destination focus, import support, and quest-log switching.", level = 1 },
                { text = "Added per-row delete icons", level = 1 },
                { text = "Added checkbox multi-select for queues and destinations.", level = 1 },
                { text = "Added bulk delete icons inside the panel/detail borders.", level = 1 },
                { text = "Added context menus for queue rows and destination rows.", level = 1 },
                { text = "Guide queues are read-only.", level = 1 },
                { text = "Added `/awp queue` commands for panel/open/show, list/ls, use, clear, remove/rm, move, import/paste/ttpaste, and help.", level = 1 },
            }},
            { title = "Manual click queue prompt", entries = {
                { text = "Added Manual Click Queue Behavior with Create New Queue, Replace Active, Append, and Ask.", level = 1 },
                { text = "Default mode is `replace`.", level = 1 },
                { text = "Unknown/invalid saved mode values normalize to `create`.", level = 1 },
                { text = "Ask mode opens a prompt so each manual destination can be placed as a new queue, replacement, or appended to the existing queue.", level = 1 },
                { text = "Ask mode is integrated with user waypoint and map pin takeover flows.", level = 1 },
                { text = "Added help/preview/search metadata for the prompt and behavior values.", level = 1 },
            }},
            { title = "Blizzard, TomTom, and addon takeovers", entries = {
                { text = "Expanded takeover coverage for:", level = 1 },
                { text = "User waypoints.", level = 2 },
                { text = "Quests and supertracked quests.", level = 2 },
                { text = "Area POIs.", level = 2 },
                { text = "Vignettes.", level = 2 },
                { text = "Taxi destinations.", level = 2 },
                { text = "Gossip POIs.", level = 2 },
                { text = "Dig sites.", level = 2 },
                { text = "Housing plots.", level = 2 },
                { text = "Added shared Blizzard takeover core handling for map pin changed/cleared behavior and adoption retries.", level = 1 },
                { text = "Added quest-backed manual metadata for quest ID, quest state, quest type, world quest type, source addon, semantic kind, and icon hints.", level = 1 },
                { text = "Improved presentation for available, incomplete, complete, repeatable, world quest, dungeon, raid, delve, racing, and travel targets.", level = 1 },
                { text = "Improved tracked, untracked, supertracked, removed, and turned-in quest cleanup behavior for both active routes and queue items.", level = 1 },
                { text = "Added unknown addon waypoint adoption controls with a toggle, whitelist, denylist, recent caller list, and chat commands.", level = 1 },
            }},
            { title = "WorldQuestTab integration", entries = {
                { text = "Added `integrations/worldquesttab_takeover.lua`.", level = 1 },
                { text = "WorldQuestTab quest pin clicks now route through the v4 routing pipeline.", level = 1 },
                { text = "Captures title, quest ID, map, coordinates, source addon, and quest context from WorldQuestTab where available.", level = 1 },
                { text = "Falls back to Blizzard quest APIs when WorldQuestTab data is not ready.", level = 1 },
            }},
            { title = "External waypoint source registry", entries = {
                { text = "Added `integrations/external_waypoint_sources.lua`.", level = 1 },
                { text = "Added metadata descriptors for SilverDragon and RareScanner.", level = 1 },
                { text = "Centralized external source normalization, display names, transient behavior, stack/path matching, and icon keys.", level = 1 },
                { text = "Replaced scattered SilverDragon/RareScanner checks in routing, queues, presentation, and world overlay content with registry helpers.", level = 1 },
                { text = "Persisted source keys remain lowercase.", level = 1 },
            }},
            { title = "World overlay architecture", entries = {
                { text = "Renamed the internal namespace to `NS.Internal.WorldOverlay`.", level = 1 },
                { text = "Split the former `world_overlay/native/` folder into:", level = 1 },
                { text = "`world_overlay/core/`", level = 2 },
                { text = "`world_overlay/assets/`", level = 2 },
                { text = "`world_overlay/pinpoint/`", level = 2 },
                { text = "`world_overlay/presentation/`", level = 2 },
                { text = "`world_overlay/runtime/`", level = 2 },
                { text = "Split API, config, state, icons, quest types, colors, content, frames, host, render, plaques, and plaque animation into focused modules.", level = 1 },
                { text = "Moved shared textures from `media/world-overlay/waypoint/` to `media/world-overlay/`.", level = 1 },
                { text = "Moved plaque textures into `media/world-overlay/plaques/`.", level = 1 },
            }},
            { title = "World overlay presentation", entries = {
                { text = "Moved icon specs and quest type handling into `world_overlay/assets/`.", level = 1 },
                { text = "Moved color and content presentation into `world_overlay/presentation/`.", level = 1 },
                { text = "Fixed atlas/texture carryover by resetting texture coordinates before applying atlas icons in `world_overlay/presentation/content.lua`.", level = 1 },
                { text = "Added Gray as a neutral preset.", level = 1 },
                { text = "Waypoint footer text defaults to Gray, while Auto uses contextual icon/spec tint.", level = 1 },
                { text = "Removed the old None color option because it because it was identical to White which we already offered.", level = 1 },
                { text = "Color dropdown options are alphabetized (excluding Custom) and include Auto, Custom, Blue, Cyan, Gold, Gray, Green, Pink, Purple, Red, Silver, and White.", level = 1 },
                { text = "Added shared Auto dropdown preview text explaining contextual target hints.", level = 1 },
                { text = "Added icon/tint support for gossip services, external sources, quest families, world quests, racing quests, dungeons, raids, delves, portals, taxis, inns, route legs, and travel actions.", level = 1 },
                { text = "Available quest POIs no longer show in-progress objective subtext before the quest is accepted.", level = 1 },
                { text = "Quest objective text refresh now uses shared quest helpers and cache invalidation.", level = 1 },
            }},
            { title = "Pinpoint, waypoint, and navigator", entries = {
                { text = "Moved plaque assets into the plaque media folder.", level = 1 },
                { text = "Added help media for overlay base/fade, navigator, small navigator, pinpoint, pinpoint off, pinpoint plaque off, and all footer modes.", level = 1 },
                { text = "Improved display state cleanup around waypoint, pinpoint, navigator, arrival, and hidden transitions.", level = 1 },
            }},
            { title = "TomTom arrow skins", entries = {
                { text = "Added a TomTom arrow skin framework system in `core/arrowskins.lua`.", level = 1 },
                { text = "Added AWP, AWP Bomber, AWP Modern, Alliance, and Horde skins.", level = 1 },
                { text = "Each new skin ships nav, arrival, and specular assets as appropriate.", level = 1 },
                { text = "Kept Starlight and Stealth Zygor mirror skins when Zygor is loaded.", level = 1 },
                { text = "Added skin preset support for single-image custom arrows, TomTom classic/modern layouts, and Zygor mirror/full sprite layouts.", level = 1 },
                { text = "Added per-skin options previews.", level = 1 },
                { text = "Fixed preview key collisions for skins with spaces/custom IDs.", level = 1 },
                { text = "Preserved the last selected custom skin when toggling Use Custom Arrow Skin off and on.", level = 1 },
            }},
            { title = "Options UI", entries = {
                { text = "Replaced the old options panel with a custom options panel under `interface/options/`.", level = 1 },
                { text = "Added About, General, TomTom Arrow, World Overlay, Waypoint, Pinpoint, Navigator, and conditional Zygor sections.", level = 1 },
                { text = "Added option search, filters, release notes, preview pane, dropdown value previews, and reusable widgets.", level = 1 },
                { text = "Added image previews for option sections, arrow skins, Zygor compact/background modes, manual queue prompts, overlay enable/fade states, context display variants, waypoint/beacon/footer modes, pinpoint modes, plaque styles, navigator, and special travel button scale.", level = 1 },
                { text = "Added search metadata for settings/sub-options that were rendered in `canvas_sections.lua` but not discoverable from `Data.OPTIONS`.", level = 1 },
                { text = "Added Detected Addon Callers UI with allow/deny controls.", level = 1 },
                { text = "The options window remembers its on-screen position.", level = 1 },
                { text = "Added a new Zygor arrow conflict prompt.", level = 1 },
            }},
            { title = "Help, screenshots, and documentation", entries = {
                { text = "Refreshed help pages for Overview, Arrow and Guide, World Overlay, Waypoint and Navigator, Pinpoint and Plaque, Customization, Commands, and What's New.", level = 1 },
                { text = "Added help screenshots for AWP arrow skins, Zygor arrow/guide modes, manual queue prompts, queue UI list/detail views, Blizzard POI and SilverDragon adoption, options panels, overlay base/fade states, context display variants, waypoint/beacon/footer modes, navigator, pinpoint modes, plaque styles, and special travel buttons.", level = 1 },
                { text = "Replaced old ZWP option media with AWP option and options-general media.", level = 1 },
            }},
            { title = "Commands and aliases", entries = {
                { text = "Added `/awp backend direct|zygor|mapzeroth|farstrider`.", level = 1 },
                { text = "Added `/awp queue ...` with `panel`, `open`, `show`, `list`, `ls`, `use`, `clear`, `remove`, `rm`, `move`, `import`, `paste`, `ttpaste`, and `help`.", level = 1 },
                { text = "Added `/awp untrackclear` and `/awp untrackedclear`.", level = 1 },
                { text = "Added `/awp addontakeover`, `/awp unknownaddons`, and `/awp addonwaypoints`.", level = 1 },
                { text = "Added/expanded diagnostics:", level = 1 },
                { text = "`/awp routedump` / `/awp routecheck`", level = 2 },
                { text = "`/awp routeenv` / `/awp routenv` / `/awp envroute`", level = 2 },
                { text = "`/awp traveldiag` / `/awp tdiag`", level = 2 },
                { text = "`/awp churn`", level = 2 },
                { text = "`/awp churnmem` / `/awp churnphases`", level = 2 },
                { text = "`/awp resolvercases` / `/awp resolvercase`", level = 2 },
                { text = "`/awp stepdebug`", level = 2 },
                { text = "`/awp waytype`", level = 2 },
                { text = "`/awp plaque` / `/awp pinpoint`", level = 2 },
                { text = "Added/kept aliases:", level = 1 },
                { text = "`/awp options` / `/awp config`", level = 2 },
                { text = "`/awp manualclear` / `/awp autoclear`", level = 2 },
                { text = "`/awp trackroute` / `/awp trackedroute`", level = 2 },
                { text = "`/awp questclear` / `/awp superquestclear`", level = 2 },
                { text = "`/awp compact` / `/awp guidechrome` / `/awp guidehover`", level = 2 },
                { text = "`/awp help` / `/awp tour`", level = 2 },
                { text = "`/awp changelog` / `/awp whatsnew` / `/awp whatnew` / `/awp new`", level = 2 },
                { text = "Existing status, debug, diag, mem, skin, scale, routing, cleardistance, search, and repair commands continue under `/awp`.", level = 1 },
            }},
            { title = "Diagnostics", entries = {
                { text = "Expanded `/awp waytype` for live overlay target inspection and preview targets.", level = 1 },
                { text = "Added source-aware waytype output for guide provider, quest hints, source addon, icon source, atlas/texture, tint, route leg, quest type, and quest status.", level = 1 },
                { text = "Expanded route diagnostics with active source, backend, selected backend, carrier source, carrier kind, route legs, route outcome, current special action, and route environment.", level = 1 },
                { text = "Expanded churn diagnostics with resolver hits/misses, manual metadata lookup, route plan accept/skip counts, backend invalidations, driver updates, world overlay updates, host sync, and optional phase memory.", level = 1 },
                { text = "Expanded guide diagnostics for Zygor, APR, and WoWPro provider-specific output.", level = 1 },
            }},
            { title = "Quest text and presentation helpers", entries = {
                { text = "Added `core/quest_text.lua`.", level = 1 },
                { text = "Added shared quest helpers for:", level = 1 },
                { text = "quest titles.", level = 2 },
                { text = "exact indexed objective text.", level = 2 },
                { text = "first unfinished objective or ready-to-turn-in text.", level = 2 },
                { text = "Updated world overlay content to reuse shared quest helpers while preserving cache behavior.", level = 1 },
                { text = "Shared quest text helpers are now used by takeovers and guide presentation layers instead of duplicating Blizzard quest API calls.", level = 1 },
                { text = "Quest cache invalidation now reacts to quest accepted, removed, turned in, completed, progress, gossip, and quest log update flows.", level = 1 },
            }},
            { title = "Search and repair", entries = {
                { text = "Preserved `/awp search` support for services, profession trainers, profession workshops, vendor fallback, repair fallback, and aliases but only functions when Zygor is installed and enabled.", level = 1 },
                { text = "Updated command/help text for the renamed addon and v4 routing backend behavior.", level = 1 },
                { text = "Kept `/awp repair` for current TomTom/Zygor external setting repair where relevant.", level = 1 },
                { text = "Removed old pre-v4 SavedVariables migration behavior from repair/default application.", level = 1 },
            }},
            { title = "Stability and polish", entries = {
                { text = "Improved reload/login behavior so the last controlling source is restored where possible.", level = 1 },
                { text = "Fixed untrack-clear behavior so queue items are not removed when the setting is disabled.", level = 1 },
                { text = "Added external clear detection and queue preservation for manual, transient, and guide-backed routes.", level = 1 },
                { text = "Reduced icon flicker/stale state when switching between addon POIs, gossip POIs, quest pins, atlas icons, texture icons, and route icons.", level = 1 },
                { text = "Improved TomTom Arrow suppression for WoWPro and other guide-provider signals to reduce protected-function taint risk.", level = 1 },
                { text = "Added guards so APR, WoWPro, and Zygor can retake route authority after another provider was active.", level = 1 },
                { text = "Improved title/subtext mirroring so provider presentation flows through the carrier and overlay consistently.", level = 1 },
            }},
        },
    },
}
