local NS = _G.ZygorWaypointNS

NS.CHANGELOG_DATA = {
    {
        version = "3.1b",
        sections = {
            { title = "Quest takeover reliability", entries = {
                "Quest takeover destinations that are initially unresolved now retry, fixing cases where quest data wasn't ready at the moment of supertracking or watch.",
                "Pending adoption retries are cancelled immediately when the supertracked quest changes, is cleared, or the watch is removed, preventing stale routes from firing.",
            }},
            { title = "World overlay fixes", entries = {
                "World overlay is now suppressed on maps that do not support user waypoints via C_Map.CanSetUserWaypointOnMap. TomTom and Zygor navigation continue working normally on those maps when supported.",
            }},
        },
    },
    {
        version = "3.1",
        sections = {
            { title = "Blizzard supertracking and supertracked quest routing", entries = {
                "Added a new Blizzard supertracking takeover to the bridge that routes them through Zygor.",
                "Added optional auto-routing setting in the options for newly watched Blizzard quests.",
                "Added adoption and cleanup for explicit Blizzard map/user waypoints through the same manual routing flow.",
                "Quest-backed manual destinations now refresh automatically when quest destinations move and clear when the quest is turned in, removed, untracked, or no longer resolves.",
            }},
            { title = "Quest-backed manual presentation", entries = {
                "Quest-backed manual destinations now carry quest metadata through bridge snapshotting, explicit removal handling, and follow-up routing.",
                "Native overlay icons now resolve quest-aware presentation for quest-backed manual and route destinations instead of falling back to generic manual/travel glyphs.",
                "Added quest objective / ready-to-turn-in subtext support for supertracked quests.",
                "Added native overlay quest cache invalidation so quest icon and subtext changes react correctly to quest log updates.",
            }},
            { title = "New controls, settings, and help coverage", entries = {
                "Added `Auto-Route Tracked Quests` and `Auto-Clear Supertracked Quests on Arrival` settings.",
                "Added `/zwp trackroute` and `/zwp questclear` commands plus status output coverage for both toggles.",
                "Updated in-game help text for tracked quests, supertracked quest arrival clearing, and related manual clear behavior.",
                "Corrected the Steampunk plaque preview asset reference in the help pages.",
            }},
            { title = "Overlay and Blizzard visual handling", entries = {
                "Improved SuperTrackedFrame suppression refresh behavior after login, user waypoint changes, and supertracking changes. This should resolve cases where the Blizzard supertracked diamond became visible.",
                "Blizzard supertracked waypoints now integrate more cleanly with arrival auto-clear rules and explicit removal behavior.",
            }},
            { title = "Performance enhancements", entries = {
                "Reduced movement churn by skipping arrow description normalization when the main arrow title is already present.",
                "Added route-bundle caching so route title, travel, and semantic resolution are reused while live route inputs stay stable.",
                "Reused content-signature and cache-key buffers and added quest type / quest subtext caches to reduce table churn in hot paths.",
            }},
        },
    },
    {
        version = "3.0",
        sections = {
            { title = "Major addon rewrite", entries = {
                "Rebuilt ZygorWaypoint into a more modular system with clearer separation between core logic, bridge behavior, Zygor integration, world overlay systems, interface code, and documentation.",
                "Reworked internal state handling for startup, database/version tracking, bridge state, overlay state, and resolver state.",
                "Replaced older monolithic behavior with a more structured architecture that is easier to maintain, extend, and debug.",
            }},
            { title = "New native 3D world overlay system", entries = {
                "Added a fully native 3D in-world overlay system for active destinations.",
                "Introduced three overlay presentation modes:",
                "**Waypoint** for long-range in-world destination display",
                "**Pinpoint** for close-range destination presentation",
                "**Navigator** for off-screen directional guidance",
                "Added smoother transition handling between overlay modes to reduce flicker near handoff thresholds.",
                "Added explicit integration with Blizzard navigation frame lifecycle events.",
                "Added shared overlay content snapshots so the bridge and overlay stay in sync on destination context.",
                "ZygorWaypoint now includes its own native waypoint/overlay system and no longer depends on WaypointUI.",
                "WaypointUI can still be used if you prefer it, but it is no longer recommended and is no longer officially supported by ZygorWaypoint.",
            }},
            { title = "Overlay customization and presentation", entries = {
                "Added extensive 3D overlay settings for:",
                "enable/disable",
                "fade on hover",
                "context display mode",
                "waypoint size, opacity, scaling limits, and vertical offset",
                "beacon style and opacity",
                "footer text behavior",
                "pinpoint mode, size, opacity, and destination info display",
                "navigator size, opacity, distance, and dynamic distance behavior",
                "Added multiple pinpoint plaque styles:",
            }},
            { title = "Default", entries = {
            }},
            { title = "Glowing Gems", entries = {
            }},
            { title = "Horde", entries = {
            }},
            { title = "Alliance", entries = {
            }},
            { title = "Modern", entries = {
            }},
            { title = "Steampunk", entries = {
                "Added color customization for overlay text, icons, beacon, plaque, animated elements, pinpoint chevrons, and navigator arrow.",
                "Added overlay support for multiple icon/content families including guide, manual, corpse, travel, portal, taxi, inn, dungeon, raid, delve, and supported external waypoint sources.",
            }},
            { title = "Smarter bridge lifecycle and visibility handling", entries = {
                "Reworked the TomTom/Zygor bridge around explicit lifecycle and visibility states instead of simple visible/hidden behavior.",
                "Hidden-guide handling now better distinguishes normal hidden state, manual/corpse override state, and cinematic state.",
                "Added improved transition handling for:",
                "login/startup",
                "loading screens",
                "cinematics and movies",
                "death / ghost / alive transitions",
                "guide show/hide changes",
                "Added coalesced hook-driven tick scheduling and additional debounce/suppression logic to reduce stale fallback arrows and sync issues.",
                "Added better tracking for deliberate manual removal versus transient waypoint state changes.",
            }},
            { title = "Improved TomTom routing and external waypoint support", entries = {
                "Reworked startup routing so existing TomTom waypoints can be adopted after both addons finish loading.",
                "Added retry handling for early startup cases where Zygor pointer objects are not ready yet.",
                "Improved distinction between bridge-owned and external TomTom waypoints.",
                "Added source-aware handling for external waypoint creators, including support paths for addons such as:",
            }},
            { title = "SilverDragon", entries = {
            }},
            { title = "RareScanner", entries = {
                "Improved cleanup and follow-up routing behavior for external/manual routes.",
                "Manual waypoints now preserve meaningful names instead of falling back to generic waypoint labels.",
            }},
            { title = "Queue routing for imported /ttpaste waypoints", entries = {
                "Added ordered queue support for multi-waypoint imports such as TomTom paste.",
                "Added queue state tracking for:",
                "queued entries",
                "active vs suspended state",
                "current active index",
                "remaining entries",
                "Added queue resume behavior so routing can continue from a later selected queued point instead of restarting the whole run.",
                "Manual arrival clear behavior now respects queued routes so only the active queued target auto-clears and advances the queue.",
            }},
            { title = "Better Zygor extraction and target handling", entries = {
                "Reworked waypoint extraction so titles, ownership, source, coordinates, and route semantics are resolved more reliably from live Zygor state.",
                "Improved distinction between:",
                "guide-owned waypoints",
                "manual waypoints",
                "corpse waypoints",
                "route-like waypoints",
                "route proxies",
                "pointer-only fallbacks",
                "Added better handling for manual route proxy transitions so routed manual destinations do not briefly collapse into incorrect fallback state.",
                "Added improved canonical target handling so guide route legs reflect the current guide goal more accurately.",
                "Added stronger guide-step suppression checks so forced no-waypoint states remain authoritative.",
            }},
            { title = "Guide resolver overhaul", entries = {
                "Rebuilt the guide resolver as a more structured subsystem rather than a single opaque implementation.",
                "Split resolver behavior into clearer responsibilities for facts, live context, scanning, presentation context, snapshot generation, resolution logic, and test cases.",
                "Improved goal/title/subtext selection in complex guide situations, including multi-goal steps, detours, helper actions, and fallback cases.",
                "Added better route-presentation gating so guide-owned route legs and non-guide targets are handled more cleanly.",
                "Added internal resolver case coverage to protect parity and document approved behavior improvements.",
            }},
            { title = "Overlay icon and quest-type improvements", entries = {
                "Added rich quest-type handling for:",
                "Normal Quests",
                "Daily Quests",
                "Weekly Quests",
                "Important Quests",
                "Campaign Quests",
                "Legendary Quests",
                "Artifact Quests",
                "Calling Quests",
                "Meta Quests",
                "Recurring/Repeatable Quests",
                "Quest families now also track available, incomplete, and complete states using combined Blizzard and Zygor data.",
                "Improved travel and destination presentation for special route types such as portal, taxi, inn, dungeon, raid, and delve targets.",
            }},
            { title = "Arrow presentation improvements", entries = {
                "TomTom remains the primary arrow display surface.",
                "Reworked the arrow presentation layer around the newer bridge behavior.",
                "Preserved and expanded support for the custom Zygor-style TomTom skins:",
            }},
            { title = "Starlight", entries = {
            }},
            { title = "Stealth", entries = {
                "Improved scale handling plus navigation/arrival layout behavior for the custom skins.",
                "Added more consistent arrow alignment behavior when anchoring TomTom to Zygor text.",
                "Added visual suppression handling for Zygor special travel icon states.",
                "Added safer behavior around Zygor arrow visibility and combat-sensitive paths which should help prevent taint issues.",
            }},
            { title = "Guide viewer presentation improvements", entries = {
                "Compact guide mode has been further improved.",
                "Added separate compact/background display modes for:",
                "visible step rows only until mouseover",
                "background fade mode",
                "background + line color fade mode",
                "Reworked viewer handling to be more robust and less fragile than the earlier compact-mode approach.",
            }},
            { title = "Search, help, diagnostics, and preview tools", entries = {
                "Expanded `/zwp search` support for:",
                "common services",
                "profession trainers",
                "profession workshops",
                "Vendor search now falls back to **Repair** when Zygor fails to produce a vendor route.",
                "Added a richer in-game help system with pages for:",
                "Overview",
                "Arrow and Guide",
                "World Overlay",
                "Waypoint and Navigator",
                "Pinpoint and Plaque",
                "Customization",
                "Commands",
                "What's New",
                "Added or expanded command support for:",
                "`/zwp help`",
                "`/zwp changelog`",
                "`/zwp options`",
                "`/zwp skin`",
                "`/zwp scale`",
                "`/zwp routing`",
                "`/zwp align`",
                "`/zwp manualclear`",
                "`/zwp cleardistance`",
                "`/zwp compact`",
                "`/zwp search`",
                "`/zwp repair`",
                "Kept support for multiple alias forms where applicable.",
                "Added richer diagnostics and preview tooling for resolver output, overlay content/icon families, travel semantics, memory usage, churn/per-tick allocation pressure, plaque previews, and quest-type previews.",
            }},
            { title = "Settings and UI overhaul", entries = {
                "Rebuilt the settings UI around Blizzard's modern Settings API.",
                "Expanded the addon settings into clearer top-level categories:",
            }},
            { title = "ZygorWaypoint", entries = {
            }},
            { title = "TomTom Arrow", entries = {
            }},
            { title = "World Overlay", entries = {
            }},
            { title = "World Overlay > Waypoint", entries = {
            }},
            { title = "World Overlay > Pinpoint", entries = {
            }},
            { title = "World Overlay > Navigator", entries = {
                "Added an About card with direct links to Help and What's New.",
            }},
            { title = "Upgrade, compatibility, and repair behavior", entries = {
                "Added addon version tracking so the addon can determine when to show What's New and when legacy repair/migration behavior should run.",
                "Added one-time legacy 2.x migration/auto-repair behavior for upgrades into 3.0.",
                "Added character-scoped handling for WaypointUI recommendation prompts/version tracking as well as SavedVariable cleanup moving from 2.X.",
                "The addon now ships its own overlay backend and is no longer limited by the previous WaypointUI compatibility layer.",
                "`/zwp repair` now restores the core external settings ZygorWaypoint depends on, including fixing default Zygor and TomTom configuration values.",
                "First login after upgrading from 2.X runs the legacy repair automatically.",
            }},
            { title = "Documentation and changelog delivery", entries = {
                "Added dedicated in-game help/changelog data rather than relying only on static README text.",
                "Added richer What's New / changelog presentation in-game.",
                "Updated the documented addon surface to better reflect current slash commands, settings UI, help UI, routing behavior, and overlay behavior.",
            }},
            { title = "Known limitations", entries = {
                "Waypoint text now scales based on distance, but due to current Blizzard font-scaling limitations the transition may appear slightly sluggish or step-like instead of perfectly smooth.",
                "This is a known limitation and is not fixable right now.",
            }},
        },
    },
}
